### ISSUE TITLE
AttributeError: 'StoreModule' object has no attribute 'EpicBackend'

### ISSUE THREAD

**Issue by Andredroner1** [Ayowel/renpy-epicgames-eos#1]
Good afternoon, I wanted to use your extension, for his visual novel, I kind of did everything according to the instructions, but, I get strange error, please help me understand what I did wrong. 

`
File "game/epic.rpy", line 17, in script

init -1499 python:

File "game/epic.rpy", line 17, in script

init -1499 python:

File "game/epic.rpy", line 18, in <module>
achievement.backends.insert(0, epicapi.EpicBackend())

AttributeError: 'StoreModule' object has no attribute 'EpicBackend'
`

Videos - https://utreon.com/v/DwHCwXGATDW

It happens when trying to run from the launcher - and just before actually starting

Put all the files into the game directory - also tried the root of the project directory, but no luck there either.

**Comment by SlurpyToad** [comment]
Same here too

**Comment by SlurpyToad** [comment]
This is with RenPy 8.0.3, by the way

**Comment by SlurpyToad** [comment]
I’ll give that a go now.

Nicholas

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Ayowel** [comment]
Strange. I'll look into it tomorrow, thank you for testing

**Comment by SlurpyToad** [comment]
A video of it is here : https://utreon.com/v/SBl7SxdeSk6

**Comment by SlurpyToad** [comment]
Hello

The lint contains :

`Ren'Py 8.0.3.22090809 lint report, generated at: Thu Apr 13 14:04:08 2023

game/init/initcharacters.rpy:31 Image oldergrendel happy uses file 'images/characters/grendel_fryingpan_1.png', which is not loadable.

game/init/initcharacters.rpy:36 Image oldergrendel pleased uses file 'images/characters/grendel_fryingpan_2.png', which is not loadable.

game/init/initcharacters.rpy:41 Image oldergrendel worried uses file 'images/characters/grendel_fryingpan_3.png', which is not loadable.

game/init/initcharacters.rpy:46 Image oldergrendel embarrassed uses file 'images/characters/grendel_fryingpan_4.png', which is not loadable.

game/init/initcharacters.rpy:51 Image oldergrendel curious uses file 'images/characters/grendel_fryingpan_5.png', which is not loadable.

game/init/initcharacters.rpy:56 Image oldergrendel annoyed uses file 'images/characters/grendel_fryingpan_6.png', which is not loadable.

game/init/initcharacters.rpy:61 Image oldergrendel neutral uses file 'images/characters/grendel_fryingpan_7.png', which is not loadable.

game/init/initcharacters.rpy:66 Image oldergrendel asleep uses file 'images/characters/grendel_fryingpan_8.png', which is not loadable.

game/init/initcharacters.rpy:71 Image oldergrendel surprised uses file 'images/characters/grendel_fryingpan_9.png', which is not loadable.

game/init/initcharacters.rpy:76 Image oldergrendel scheming uses file 'images/characters/grendel_fryingpan_10.png', which is not loadable.

game/init/initcharacters.rpy:81 Image oldergrendel evil_shocked uses file 'images/characters/grendel_fryingpan_11.png', which is not loadable.

game/init/initcharacters.rpy:86 Image oldergrendel furious uses file 'images/characters/grendel_fryingpan_12.png', which is not loadable.


Statistics:

The game contains 11,001 dialogue blocks, containing 80,135 words and 469,622
characters, for an average of 7.3 words and 43 characters per block.

The game contains 36 menus, 788 images, and 79 screens.

Character statistics (for default language):
 * player has 3,173 blocks of dialogue.
 * olderGrendel has 2,558 blocks of dialogue.
 * bree has 875 blocks of dialogue.
 * mum has 817 blocks of dialogue.
 * principal has 309 blocks of dialogue.
 * ricky has 291 blocks of dialogue.
 * lorinda has 249 blocks of dialogue.
 * kitchenManager has 218 blocks of dialogue.
 * councilHead has 217 blocks of dialogue.
 * aldoBevin has 178 blocks of dialogue.
 * myrtle and shadowCommander have 153 blocks of dialogue each.
 * missJoy has 151 blocks of dialogue.
 * lorelei has 149 blocks of dialogue.
 * isai has 142 blocks of dialogue.
 * pMum has 109 blocks of dialogue.
 * alice has 108 blocks of dialogue.
 * pupil4 has 90 blocks of dialogue.
 * mumBoss has 78 blocks of dialogue.
 * patrol1 has 76 blocks of dialogue.
 * pDad has 75 blocks of dialogue.
 * shadowMessenger has 69 blocks of dialogue.
 * exClassRep has 67 blocks of dialogue.
 * majorDoGooder has 64 blocks of dialogue.
 * no1 and theBoss have 62 blocks of dialogue each.
 * patrol2 has 61 blocks of dialogue.
 * radioPresenter has 52 blocks of dialogue.
 * siu has 37 blocks of dialogue.
 * councilMember has 36 blocks of dialogue.
 * orphanDirector has 31 blocks of dialogue.
 * councilAgent and pupil5 have 28 blocks of dialogue each.
 * kid has 21 blocks of dialogue.
 * shopManager has 19 blocks of dialogue.
 * councilEmployee1, librarian, professorGrief2, and wife have 15 blocks of
   dialogue each.
 * nurse and radioController have 13 blocks of dialogue each.
 * myrtleLarge and william have 11 blocks of dialogue each.
 * assassin, newsReader, and tannoy have 10 blocks of dialogue each.
 * captain, custodianSecurity, and drNotNice have 9 blocks of dialogue each.
 * councilEmployee2 has 8 blocks of dialogue.
 * narrator has 6 blocks of dialogue.
 * door, lorindaLarge, presenter, and tvPresenter have 3 blocks of dialogue
   each.
 * libraryPatron and williamDad have 2 blocks of dialogue each.


Lint is not a substitute for thorough testing. Remember to update Ren'Py
before releasing. New releases fix bugs and improve compatibility.
`

The odd thing is clearing the RPYC files and Check Script works, but do it again and it doesn't

If you're able to do remote access that will be fine - I've only got Discord unfortunately

**Comment by Ayowel** [comment]
https://discord.gg/4D8DTKeT

**Comment by Ayowel** [comment]
This specific issue is solved. Closing in favor of #2 for clarity.
