### ISSUE TITLE
'epicapi' is not defined

### ISSUE THREAD

**Issue by GamesByKinmoku** [Ayowel/renpy-epicgames-eos#6]
Hello,

I believe I've followed the steps correctly, but I get this crash when attempting to load my game:

`[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/epic.rpy", line 21, in script
    init -1499 python:
  File "game/epic.rpy", line 22, in <module>
    achievement.backends.insert(0, epicapi.EpicBackend())
NameError: name 'epicapi' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/epic.rpy", line 21, in script
    init -1499 python:
  File "/Applications/renpy-7.6.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.6.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/epic.rpy", line 22, in <module>
    achievement.backends.insert(0, epicapi.EpicBackend())
NameError: name 'epicapi' is not defined

Darwin-23.1.0-arm64-arm-64bit arm64
Ren'Py 7.6.3.23091805
VIDEOVERSE 1.1.1.0
Tue Jan 23 15:14:37 2024
[/code]
`

**Comment by Ayowel** [comment]
Hi,

Thank you for your interest in the project.
This error should only occur if the extension was not loaded properly.

Could you check that you have a file called `epic_eos.rpe` in the directory where you created `epic.rpy` ?

**Comment by GamesByKinmoku** [comment]
Hello, thanks for your reply. It was in the wrong folder and now it works. Thank you for the help!
