### ISSUE TITLE
Achievements not working

### ISSUE THREAD

**Issue by GamesByKinmoku** [Ayowel/renpy-epicgames-eos#7]
Hello again. Sorry to open an issue for this, but my achievements are still not working on epic. Can I check that the code for the achievements in game is correct?

In script.rpy:

label splashscreen:
    $ status.game_menu_screen = None

    if 'epicapi' in globals():
        $ epicapi.init()

    show splash

    return

I've included epic.rpy and epic_eos.rpe in my game folder (with my own IDs). I also have 01epic_dev.rpy (with my own sandbox IDs) but I'm unsure what it's used for. I have the DevAuthTool and have made a key but do not understand what I'm meant to be using it for. It says the key has never been used, anyway.

Libs are also included in the top folder (beside game folder).

I haven't changed the achievement code at all (where the achievements register). Right now, I've left it the same as Steam... Is that correct?

if not achievement.has("chapter5"):
    $ achievement.grant("chapter5")
    init:
        $ achievement.register("chapter5")
        $ achievement.sync()
    $ achievement.sync()
        
Sorry to ask. I sent a support ticket to Epic last week but they have not replied and I'm at a loss. I'd really like to include epic achievements in my game.

**Comment by Ayowel** [comment]
Hi, thank you again for your interest in the project.

> I also have 01epic_dev.rpy (with my own sandbox IDs) but I'm unsure what it's used for.

When running a game through the Epic Games launcher, the launcher provides information to the game to permit login. When developing the game (and running it out of the launcher), this information is not available and `01epic_dev.rpy` should be used to provide information that allows you to login despite the launcher not providing it.

> I have the DevAuthTool and have made a key but do not understand what I'm meant to be using it for.

When working on your game, run the DevAuthTool, authenticate in it and ensure the name of the key matches the `config.epic_userpassword`. From this point on, and as long as the DevAuthTool is running, your game should have no issue logging you into Epic Game's infrastructure.

> It says the key has never been used, anyway.

This should not happen if you start your game after logging in with the DevAuthTool. Ensure that the `config.epic_userlogin` is set to `'localhost:6547'` (with 6547 the port number the DevAuthTool asks for when starting), that `config.epic_authtype` is set to `'developer'`, and that `config.epic_userpassword` matches the key you set after logging in with the DevAuthTool.

> I haven't changed the achievement code at all (where the achievements register). Right now, I've left it the same as Steam... Is that correct?

Yes

If you'd like to vocal/set-up a screen-sharing session so we can take a look, contact me on [discord](https://discord.gg/XSBezHkR8p)

**Comment by Ayowel** [comment]
Fixed via discord, providing the short-form solution here.

1 - When testing with the Epic Dev Auth tool, the `config.epic_userpassword` should match the key shown in the following image, and not one of the other values visible in the 'credentials' section

![fixit](https://github.com/Ayowel/renpy-epicgames-eos/assets/8655467/d5b5e242-bbd1-4b8d-ad4a-bb865030983f)

2 - When testing, ensure that the achievements are cleared or that no check is set-up before granting the achievements. With code like the following, achievements must be cleared before they are tested (see `The login succeeds but unlocking achievements fails` in the [FAQ](https://github.com/Ayowel/renpy-epicgames-eos/wiki/Common-questions-and-issues)):

```py
if not achievement.has('my_achievement'):
    $ achievement.grant('my_achievement')
```

When testing with epic, achievements may need to be cleared manually. See `Achievements granted once stay granted even after clearing them` in the [FAQ](https://github.com/Ayowel/renpy-epicgames-eos/wiki/Common-questions-and-issues)

Thanks to Kinmoku for their patience and their help in shedding light on those issues so they could be documented.
